### ISSUE TITLE
Tests fail if CGI.pm is not installed

### ISSUE THREAD

**Issue by eserte** [mpeters/html-template#13]
Please see https://rt.cpan.org/Ticket/Display.html?id=114549

**Comment by eserte** [comment]
I see that the change was already done in the git repository, but a CPAN release is still missing...

**Comment by mpeters** [comment]
I haven't been involved in the maintenance or release of Perl modules for a while. So it's probably best that someone ask CPAN to take over maintainer status of this.

**Comment by eserte** [comment]
You could follow instructions given in http://neilb.org/2013/08/07/adoptme.html to make clear that the module is free for adoption.

**Comment by samtregar** [comment]
I'll take it back. It was my baby once, it can always come home.  My CPAN ID is SAMTREGAR.

**Comment by samtregar** [comment]
New release is going out now.  Looks like I still have permissions to do it.  Thanks for the nudge.

**Comment by samtregar** [comment]
Huh, or not - got a fail on the upload since I'm not still the maintainer.  I'll see what I can do about that.

**Comment by samtregar** [comment]
Huh, http://search.cpan.org/~leocharre/HTML-Template-Default/ claimed a namespace we're using internally!  I guess I'll change our name.

**Comment by samtregar** [comment]
Ok, fixed and 2.97 is on its way to CPAN.
