### ISSUE TITLE
Clarify relationship between CPAN releases and this repo.

### ISSUE THREAD

**Issue by markstos** [mpeters/html-template#6]
The Changes file on CPAN and the one here don't match. The one on CPAN shows releases for 2.91 through 2.94, but the Changes file here jumps from 2.9 to 2.10.

Where's the branch that corresponds with the CPAN releases?

**Comment by samtregar** [comment]
I think that's probably lost to time unless mpeters remembers.  Regardless, this is the repo for all future releases, at least until some new version control comes along and makes GitHub look as old and silly as SourceForge does now.
